import type { ContentEntry, SiteSettings } from "@/lib/content/types";

const now = new Date().toISOString();

export const defaultSettings: SiteSettings = {
  siteName: "Kotacom",
  tagline: "Percetakan dan IT Service untuk pertumbuhan bisnis modern.",
  whatsappNumber: "6281234567890",
  email: "hello@kotacom.id",
  phone: "+62 21 5555 8800",
  address: "Jakarta, Indonesia",
  nav: [
    { label: "Layanan", href: "/services" },
    { label: "Shop", href: "/shop" },
    { label: "Blog", href: "/blog" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Kontak", href: "/contact" },
  ],
  social: [
    { label: "Instagram", href: "https://instagram.com" },
    { label: "LinkedIn", href: "https://linkedin.com" },
  ],
};

export const seedContent: ContentEntry[] = [
  {
    id: "svc-brand-kit",
    type: "services",
    slug: "branding-print-kit",
    title: "Branding Print Kit",
    excerpt: "Paket cetak premium untuk materi branding bisnis yang konsisten.",
    body: "Kami merancang dan memproduksi kartu nama, company profile, katalog, dan materi promosi dengan standar warna presisi. Workflow kami mengutamakan kecepatan, kontrol kualitas, dan hasil visual yang siap dipakai tim sales.",
    status: "published",
    coverImage: null,
    meta: {
      icon: "palette",
      category: "Percetakan",
      highlights: ["Color-managed print", "Fast production", "Custom finishing"],
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc-managed-it",
    type: "services",
    slug: "managed-it-support",
    title: "Managed IT Support",
    excerpt: "Pendampingan IT harian untuk operasional kantor yang stabil.",
    body: "Tim kami membantu audit infrastruktur, setup perangkat, hardening jaringan, serta preventive maintenance. Anda mendapatkan SLA jelas, laporan periodik, dan eskalasi cepat untuk kendala kritis.",
    status: "published",
    coverImage: null,
    meta: {
      icon: "server",
      category: "IT Service",
      highlights: ["SLA response", "Network hardening", "On-site & remote"],
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-rollup",
    type: "products",
    slug: "rollup-premium",
    title: "Rollup Banner Premium",
    excerpt: "Rollup untuk event dan showroom dengan visual tajam.",
    body: "Cetak resolusi tinggi dengan material tahan lama. Cocok untuk pameran, toko, dan presentasi korporat. Tersedia opsi desain custom dan pengerjaan ekspres.",
    status: "published",
    coverImage: null,
    meta: {
      category: "Display",
      ctaType: "whatsapp",
      priceLabel: "Mulai 450rb",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prd-website",
    type: "products",
    slug: "company-profile-website",
    title: "Company Profile Website",
    excerpt: "Website performa tinggi untuk konversi lead bisnis Anda.",
    body: "Kami membangun website modern dengan struktur SEO, performa cepat, dan dashboard konten sederhana. Paket cocok untuk bisnis jasa, distribusi, maupun manufaktur.",
    status: "published",
    coverImage: null,
    meta: {
      category: "Digital",
      ctaType: "rfq",
      priceLabel: "Start from project quote",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "blog-seo",
    type: "posts",
    slug: "strategi-seo-website-jasa",
    title: "Strategi SEO Website Jasa di 2026",
    excerpt: "Prinsip SEO praktis untuk meningkatkan lead organik bisnis jasa.",
    body: "Kunci SEO modern dimulai dari struktur halaman yang jelas, kecepatan loading stabil, dan konten yang menjawab intent calon pelanggan. Fokus pada halaman layanan, FAQ berniat beli, serta artikel edukasi dengan internal linking yang rapi.",
    status: "published",
    coverImage: null,
    meta: {
      author: "Tim Kotacom",
      readTime: "5 min",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "blog-print",
    type: "posts",
    slug: "tips-persiapan-file-cetak",
    title: "7 Tips Persiapan File Sebelum Cetak",
    excerpt: "Checklist agar hasil cetak tetap akurat dan minim revisi.",
    body: "Gunakan color profile yang sesuai, pastikan bleed area aman, konversi font ke outline bila perlu, dan cek resolusi gambar minimal 300 DPI. Persiapan file yang tepat mempercepat proses dan menjaga kualitas akhir.",
    status: "published",
    coverImage: null,
    meta: {
      author: "Studio Produksi",
      readTime: "4 min",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pf-retail",
    type: "portfolio",
    slug: "rebrand-retail-chain",
    title: "Rebrand Materials for Retail Chain",
    excerpt: "Rebranding 32 outlet dengan materi print dan signage seragam.",
    body: "Project mencakup panduan visual, produksi signage, POS material, serta deployment batch by batch. Hasilnya konsistensi brand meningkat dan waktu onboarding cabang baru berkurang signifikan.",
    status: "published",
    coverImage: null,
    meta: {
      industry: "Retail",
      scope: "Brand + Print Production",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pf-manufacture",
    type: "portfolio",
    slug: "it-modernization-manufacture",
    title: "IT Modernization for Manufacture",
    excerpt: "Stabilisasi jaringan dan endpoint untuk operasi multi-site.",
    body: "Kami lakukan network segmentation, monitoring dasar, dan standardisasi endpoint policy. Downtime menurun, troubleshooting lebih cepat, dan tim internal punya dokumentasi operasional yang lebih rapi.",
    status: "published",
    coverImage: null,
    meta: {
      industry: "Manufacturing",
      scope: "Infrastructure + Support",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "page-home",
    type: "pages",
    slug: "home",
    title: "Kotacom Homepage",
    excerpt: "Halaman utama brand Kotacom.",
    body: "Kotacom menggabungkan layanan percetakan modern dan IT service untuk membantu bisnis tumbuh lebih cepat.",
    status: "published",
    coverImage: null,
    meta: {
      heroTitle: "Build Brand. Scale Operations.",
      heroSubtitle: "Partner percetakan dan IT service untuk tim yang butuh hasil cepat dan rapi.",
      primaryCta: "Konsultasi Proyek",
      primaryHref: "/contact",
    },
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];
